### PR TITLE
update README butterfly ultrasound gallery link

### PR DESCRIPTION
**Pull request by nickdnickd**

### CODE REVIEW

**Comment by jannisborn** [comment]
Thanks a lot for finding and sharing the updated link!

**Comment by rafaelblevin821** [comment]
Hi, I'm running into an error when trying to test the model. 

`test.py: error: unrecognized arguments: [-h] [--data DATA] [--weights WEIGHTS] [--m_id M_ID] [--classes CLASSES] [--folds FOLDS] [--save_path SAVE_PATH]`

Any ideas how I can rectify this? Thanks.

**Comment by nickdnickd** [comment]
> Thanks a lot for finding and sharing the updated link!

any time! Thank you for open sourcing this.

**Comment by nickdnickd** [comment]
> Hi, I'm running into an error when trying to test the model.
> 
> `test.py: error: unrecognized arguments: [-h] [--data DATA] [--weights WEIGHTS] [--m_id M_ID] [--classes CLASSES] [--folds FOLDS] [--save_path SAVE_PATH]`
> 
> Any ideas how I can rectify this? Thanks.

Hi @rafaelblevin821 This is a pull request and not the issues page, but I can try to help. 
It seems like you might have pasted this line from the README. That is actually help text for the command; in reality you usually don't use square brackets in a command `[]`. The real command looks like it can actually run with defaults if you have been using defaults all the way through (although you may have to update `data`). 

Try `python scripts/test.py` in your terminal

**Comment by rafaelblevin821** [comment]
> > Hi, I'm running into an error when trying to test the model.
> > `test.py: error: unrecognized arguments: [-h] [--data DATA] [--weights WEIGHTS] [--m_id M_ID] [--classes CLASSES] [--folds FOLDS] [--save_path SAVE_PATH]`
> > Any ideas how I can rectify this? Thanks.
> 
> Hi @rafaelblevin821 This is a pull request and not the issues page, but I can try to help. It seems like you might have pasted this line from the README. That is actually help text for the command; in reality you usually don't use square brackets in a command `[]`. The real command looks like it can actually run with defaults if you have been using defaults all the way through (although you may have to update `data`).
> 
> Try `python scripts/test.py` in your terminal

Hi, Sorry, I will post this in the issues section. 

I tried `python scripts/test.py` but got more errors.

Will continue the thread in the issues section if that is ok?

**Pull request merged**
