### PR TITLE
New data and updated metadata

### PR DESCRIPTION
**Pull request by NinaWie**
Includes
* New images from Oliviera paper and emdocs website available under CC
* Updated metadata.csv: Changed filename column so they don't include the file type anymore (because of changes from gif to mp4 etc), updated resolution and framerate with script, added rows for new data
* Add unlicensed data to gitigore
* Add other new data to sh script and crop json
* Clean notebook (clear output)
* Adopt `dataset_cleanup.py` to new file format etc

### CODE REVIEW

**Review by jannisborn — APPROVED** [review]
Great work and big improvement!
A comment on the metadata.csv: The `Used` column was supposed to indicate whether or not we used this data to assemble the size of the dataset in the Applied Sciences paper. I think this wasnt super clear and it's also a bit questionable how useful this is, especially looking forward. How did you interpret this column?

Also the paper by Arntfield et al. is available in a CC-BY-NC-ND license, so we should mention this in the metadata

**Comment by jannisborn** [comment]
Oh and we should tie this PR to the issues that it is supposed to close

**Comment by NinaWie** [comment]
Ah okay, yes as you suspected I interpreted the column differently - I thought it only indicates which data can be used for training in general. But also in this case it is not super useful, since this is basically the same as all convex data which don't have a "not used" comment in the current location column.
My suggestion: We rename the column to "Applied Sciences data" and I change the values in this column for the new data which were not part of the paper.

**Comment by NinaWie** [comment]
Ready to merge from my side, I have pushed the new metadata file and linked three issues manually (see right column of this page).

**Pull request merged**
